import type { TemplateManifest } from "@/types";
import { COMMON_VARIABLES } from "../common";

export const manifest: TemplateManifest = {
  id: "project-highlights",
  name: "Project Highlights",
  description: "Placeholder for a project-focused resume template.",
  category: "Developer",
  tags: ["Top Picks"],
  variables: COMMON_VARIABLES,
};

// TODO: Paste full LaTeX content for the Project Highlights template below.
// Make sure it exports a single `content` string using backticks (`).
export const content = String.raw`
\documentclass[10pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[default]{lato}
\usepackage{geometry}
\usepackage{xcolor}
\usepackage{enumitem}
\usepackage{paracol}
\usepackage{fontawesome5}
\usepackage{titlesec}
\usepackage{hyperref}

\geometry{left=1.5cm, right=1.5cm, top=1.25cm, bottom=1.25cm}

\definecolor{maincolor}{HTML}{000000}
\definecolor{darkgray}{HTML}{2E2E2E}

\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlength{\parskip}{3pt}

\titleformat{\section}{\large\bfseries\color{maincolor}}{}{0em}{}[\titlerule]
\titlespacing*{\section}{0pt}{6pt}{4pt}

\setlist[itemize]{leftmargin=1.2em, itemsep=2pt, topsep=2pt}

\begin{document}

%% ---- HEADER ----
{\Huge\bfseries JAYDEEP SINGH}\\[3pt]
{\large\bfseries Jaypee University of Engineering and Technology}\\[5pt]
\faAt\ \href{mailto:jd7june1999@gmail.com}{jd7june1999@gmail.com}
\quad
\faMapMarker*\ Guna, Madhya Pradesh - India
\quad
\faLinkedin\ \href{https://www.linkedin.com/in/jaydeep-singh-4ab1a3162/}{https://www.linkedin.com/in/jaydeep-singh-4ab1a3162/}

\vspace{0.4em}
\noindent\rule{\textwidth}{0.8pt}
\vspace{0.2em}

%% ---- TWO COLUMN LAYOUT ----
\setlength{\columnsep}{1.2cm}
\columnratio{0.55}
\begin{paracol}{2}

%% ---- LEFT COLUMN ----

\section{Experience}

\noindent{\large Research Intern -- IIT Indore}\\
{\bfseries Biomedical Signal Processing}\\
{\small \faCalendar\ June 2019 -- July 2019 \quad \faMapMarker*\ Indore, India}
\begin{itemize}
    \item Research and development of Biomedical Signal Processing in collaboration with IIT Indore.
    \item Working with team on design, development and integration of signal processing.
    \item Experience with performance analysis, optimizations and benchmark evaluations.
\end{itemize}

\vspace{0.3em}
\noindent\rule{\linewidth}{0.4pt}
\vspace{0.1em}

\noindent{\large Machine Learning}\\
{\bfseries Coursera}\\
{\small \faCalendar\ Oct 2018 -- Jan 2019 \quad \faMapMarker*\ Online}
\begin{itemize}
    \item Supervised Learning: trained models to recognize patterns in given data more efficiently.
    \item Worked on Support Vector Machines (SVMs, also support vector networks) which is supervised learning models with associated learning algorithms that analyze data used for classification and regression analysis.
\end{itemize}

\section{Achievements}

\begin{itemize}
    \item District level football player at Rewa under 16 age group.
    \item Scored 2nd position in inter-school Badminton Championship.
    \item Manager at IETE Students Forum (ISF), Jaypee University of Engineering \& Technology, Guna (M.P.).
\end{itemize}

\section{Technical Skills}

\begin{itemize}
    \item MATLAB, Xilinx ISE 12.1, MS Office, Proteus, Arduino
    \item C, C++, Java, Python (Beginner)
\end{itemize}

\section{Personal Skills}

\begin{itemize}
    \item Having Leadership Qualities.
    \item Ability to work under pressure.
    \item Comfortable Working Independently.
    \item Ability to take initiative to solve problems.
\end{itemize}

\section{Hobbies}

\begin{itemize}
    \item Playing badminton and video games.
    \item Listening to Music.
    \item Exploring Places.
\end{itemize}

%% ---- RIGHT COLUMN ----
\switchcolumn

\section{Education}

\noindent{\large B.Tech. (ECE) -- 9.0 CGPA}\\
{\bfseries Jaypee University of Engineering \& Technology}\\
{\small \faCalendar\ July 2016 -- Currently}

\vspace{0.5em}

\noindent{\large Higher Secondary -- 71\%}\\
{\bfseries Central Board of Secondary Education}\\
{\small \faCalendar\ 2016}

\vspace{0.5em}

\noindent{\large Secondary -- 7.8 CGPA}\\
{\bfseries Central Board of Secondary Education}\\
{\small \faCalendar\ 2014}

\section{Projects}

\noindent{\bfseries Acoustic Echo Cancellation (AEC)}
\begin{itemize}
    \item In hands-free communication, coupling between microphone and loudspeaker produces acoustic echo which needs to be cancelled, so AEC provides one of the best solutions to the control of acoustic echoes generated by hands-free audio terminals.
\end{itemize}

\vspace{0.3em}
\noindent{\bfseries Object and Edge Avoider}
\begin{itemize}
    \item Made a bot which avoids edges so that it couldn't be fallen down from height; edge is sensed by IR sensors and objects are sensed by an Ultrasonic sensor, with a servo motor to control direction.
\end{itemize}

\vspace{0.3em}
\noindent{\bfseries Smart Street Light}
\begin{itemize}
    \item Made using Arduino Nano and IR sensors. When no vehicle is present, street light dims; when a vehicle comes in front of the 1st street light the next two go bright (PWM was used).
\end{itemize}

\vspace{0.3em}
\noindent{\bfseries Home Automation}
\begin{itemize}
    \item Project consists of 2 NodeMCU, 1 Amazon Alexa dot and a Blynk app. Works on both voice recognition as well as IoT using Blynk app.
\end{itemize}

\vspace{0.3em}
\noindent{\bfseries LED Cube (4x4)}
\begin{itemize}
    \item Have made many patterns using this cube.
\end{itemize}

\vspace{0.3em}
\noindent{\bfseries Bluetooth Controlled Bot}
\begin{itemize}
    \item Consists of Arduino Uno and Bluetooth Module HC-05. Made for college fest DEXTRA 2K18 at JUET, Guna.
\end{itemize}

\end{paracol}

\end{document}

`;

