"""
Builds the Vero logo ("\\V" mark, "\\Vero" wordmark) from Cal Sans outlines.

    pip install fonttools
    curl -sLO https://github.com/google/fonts/raw/main/ofl/calsans/CalSans-Regular.ttf
    python scripts/brand/generate-logo.py CalSans-Regular.ttf

Writes, for both the marketing site and the dashboard (latex-ai-editor):
  public/brand/vero-{mark,wordmark}.svg          currentColor (inline use, follows the theme)
  public/brand/vero-{mark,wordmark}-{black,white}.svg   fixed colours (Clerk, Dodo, emails, docs)
  <app>/icon.svg                                 favicon: black mark, white in dark-mode browsers
  <brand components>/vero-logo-geometry.ts       path data for the React logo components

The backslash is not Cal Sans' own "\\" (that one leans at 0.66, much flatter
than the V). It's drawn to match the V: parallel to the V's left stroke, the
same thickness, cap height tall, with flat ends. The letters use Cal Sans'
advances and kerning (V-e -77, r-o -25).
"""
import sys
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[2]
PROJECTS = [  # (project root, app dir, brand components dir)
    (ROOT, "app", "components/brand"),
    (ROOT.parent / "latex-ai-editor", "src/app", "src/components/brand"),
]
INK, PAPER = "#0a0a0a", "#fafafa"
CAP = 700                  # Cal Sans cap height (units per em: 1000)
VIEW_H = 713               # cap height + the e/o overshoot below the baseline
SLOPE = 279 / 700          # the V's left outer edge: (262, 0) -> (-17, 700)
RIGHT_SLOPE = 277 / 700    # the V's right outer edge: (397, 0) -> (674, 700)
SLASH_W = 150              # horizontal thickness, about the V's stroke
GAP = 70                   # between the slash and the V, constant along the height
ADV = {"V": 580, "e": 572, "r": 312}  # advances after kerning (HarfBuzz)

font = TTFont(sys.argv[1])
glyphs, cmap = font.getGlyphSet(), font.getBestCmap()


def num(v: float) -> str:
    return f"{v:.1f}".rstrip("0").rstrip(".")


def glyph(ch: str, dx: float) -> str:
    pen = SVGPathPen(glyphs, ntos=num)
    glyphs[cmap[ord(ch)]].draw(TransformPen(pen, (1, 0, 0, -1, dx, CAP)))  # y down, cap top at 0
    return pen.getCommands()


def points(ch: str, dx: float):
    from fontTools.pens.recordingPen import RecordingPen
    rec = RecordingPen()
    glyphs[cmap[ord(ch)]].draw(rec)
    for _, pts in rec.value:
        for x, y in pts:  # on- and off-curve points bound the outline
            yield x + dx, y


def slash(bottom_left: float) -> str:
    top = bottom_left - SLOPE * CAP
    return f"M{num(top)} 0H{num(top + SLASH_W)}L{num(bottom_left + SLASH_W)} {CAP}H{num(bottom_left)}Z"


bx = SLOPE * CAP                       # slash top-left at x = 0
vx = bx + SLASH_W + GAP - 262          # V placed so the gap is GAP at every height
ex = vx + ADV["V"]
rx = ex + ADV["e"]
ox = rx + ADV["r"]
mark_w = vx + 674
word_w = ox + 574

# Letters hide behind the V's right stroke: visible only to the right of its outer edge.
edge = lambda y: vx + 397 + RIGHT_SLOPE * y  # font units, y up
letters = [("e", ex), ("r", rx), ("o", ox)]
strip_dx = min(edge(y) - x for ch, dx in letters for x, y in points(ch, dx)) - 24
clip_top, clip_bottom = -60, VIEW_H + 60  # svg y
clip = (
    f"M{num(edge(CAP - clip_top))} {clip_top}H{num(word_w + 200)}V{clip_bottom}"
    f"H{num(edge(CAP - clip_bottom))}Z"
)
merge = vx + 262 - bx  # slash travel until it sits inside the V's left stroke

V, e, r, o = glyph("V", vx), glyph("e", ex), glyph("r", rx), glyph("o", ox)
S = slash(bx)

def svg(view_w, view_h, paths, fill="currentColor"):
    body = "".join(f'<path d="{d}"/>' for d in paths)
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {num(view_w)} {view_h}" fill="{fill}"><title>Vero</title>{body}</svg>\n'


mark_paths, word_paths = [S, V], [S, V, e, r, o]
# Favicon: the mark centred in a square, ink by default and paper when the browser is dark.
pad = (mark_w - CAP) / 2
icon = (
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="-40 {num(-pad - 40)} {num(mark_w + 80)} {num(mark_w + 80)}">'
    f"<style>path{{fill:{INK}}}@media (prefers-color-scheme:dark){{path{{fill:{PAPER}}}}}</style>"
    + "".join(f'<path d="{d}"/>' for d in mark_paths) + "</svg>\n"
)
geometry = (
    "// Generated by marketing/scripts/brand/generate-logo.py from Cal Sans. Don't edit by hand.\n"
    "export const VERO_LOGO = {\n"
    f"  /** viewBox height: cap height {CAP} + overshoot */\n  viewH: {VIEW_H},\n"
    f"  /** cap height: the mark's viewBox height */\n  capH: {CAP},\n"
    f"  /** \\V mark width and \\Vero wordmark width, in viewBox units */\n"
    f"  markW: {num(mark_w)},\n  wordW: {num(word_w)},\n"
    f"  slash: \"{S}\",\n  V: \"{V}\",\n  e: \"{e}\",\n  r: \"{r}\",\n  o: \"{o}\",\n"
    f"  /** Region right of the V's right stroke: the letters are visible only here. */\n  clip: \"{clip}\",\n"
    f"  /** x offset that tucks \"ero\" fully behind the V. */\n  stripDX: {num(strip_dx)},\n"
    f"  /** x offset that slides the slash into the V's left stroke (they're parallel). */\n  merge: {num(merge)},\n"
    "} as const;\n"
)
for root, app_dir, components_dir in PROJECTS:
    brand = root / "public/brand"
    brand.mkdir(parents=True, exist_ok=True)
    for name, w, h, paths in (("mark", mark_w, CAP, mark_paths), ("wordmark", word_w, VIEW_H, word_paths)):
        (brand / f"vero-{name}.svg").write_text(svg(w, h, paths))
        (brand / f"vero-{name}-black.svg").write_text(svg(w, h, paths, INK))
        (brand / f"vero-{name}-white.svg").write_text(svg(w, h, paths, PAPER))
    (root / app_dir / "icon.svg").write_text(icon)
    (root / components_dir).mkdir(parents=True, exist_ok=True)
    (root / components_dir / "vero-logo-geometry.ts").write_text(geometry)
print(f"mark {num(mark_w)} x {CAP}, wordmark {num(word_w)} x {VIEW_H}, stripDX {num(strip_dx)}, merge {num(merge)}")
