"""
Builds the Vero logo ("\\V" mark, "\\Vero" wordmark) from Cal Sans outlines.

    pip install fonttools
    curl -sLO https://github.com/google/fonts/raw/main/ofl/calsans/CalSans-Regular.ttf
    python scripts/brand/generate-logo.py CalSans-Regular.ttf

Writes public/brand/vero-mark.svg, public/brand/vero-wordmark.svg and
components/brand/vero-logo-geometry.ts (used by the animated navbar logo).

The backslash is not Cal Sans' own "\\" (that one leans at 0.66, much flatter
than the V). It's drawn to match the V: parallel to the V's left stroke, the
same thickness, cap height tall, with flat ends. The letters use Cal Sans'
advances and kerning (V-e -77, r-o -25).
"""
import sys
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[2]
CAP = 700                  # Cal Sans cap height (units per em: 1000)
VIEW_H = 713               # cap height + the e/o overshoot below the baseline
SLOPE = 279 / 700          # the V's left outer edge: (262, 0) -> (-17, 700)
RIGHT_SLOPE = 277 / 700    # the V's right outer edge: (397, 0) -> (674, 700)
SLASH_W = 150              # horizontal thickness, about the V's stroke
GAP = 70                   # between the slash and the V, constant along the height
ADV = {"V": 580, "e": 572, "r": 312}  # advances after kerning (HarfBuzz)

font = TTFont(sys.argv[1])
glyphs, cmap = font.getGlyphSet(), font.getBestCmap()


def num(v: float) -> str:
    return f"{v:.1f}".rstrip("0").rstrip(".")


def glyph(ch: str, dx: float) -> str:
    pen = SVGPathPen(glyphs, ntos=num)
    glyphs[cmap[ord(ch)]].draw(TransformPen(pen, (1, 0, 0, -1, dx, CAP)))  # y down, cap top at 0
    return pen.getCommands()


def points(ch: str, dx: float):
    from fontTools.pens.recordingPen import RecordingPen
    rec = RecordingPen()
    glyphs[cmap[ord(ch)]].draw(rec)
    for _, pts in rec.value:
        for x, y in pts:  # on- and off-curve points bound the outline
            yield x + dx, y


def slash(bottom_left: float) -> str:
    top = bottom_left - SLOPE * CAP
    return f"M{num(top)} 0H{num(top + SLASH_W)}L{num(bottom_left + SLASH_W)} {CAP}H{num(bottom_left)}Z"


bx = SLOPE * CAP                       # slash top-left at x = 0
vx = bx + SLASH_W + GAP - 262          # V placed so the gap is GAP at every height
ex = vx + ADV["V"]
rx = ex + ADV["e"]
ox = rx + ADV["r"]
mark_w = vx + 674
word_w = ox + 574

# Letters hide behind the V's right stroke: visible only to the right of its outer edge.
edge = lambda y: vx + 397 + RIGHT_SLOPE * y  # font units, y up
letters = [("e", ex), ("r", rx), ("o", ox)]
strip_dx = min(edge(y) - x for ch, dx in letters for x, y in points(ch, dx)) - 24
clip_top, clip_bottom = -60, VIEW_H + 60  # svg y
clip = (
    f"M{num(edge(CAP - clip_top))} {clip_top}H{num(word_w + 200)}V{clip_bottom}"
    f"H{num(edge(CAP - clip_bottom))}Z"
)
merge = vx + 262 - bx  # slash travel until it sits inside the V's left stroke

V, e, r, o = glyph("V", vx), glyph("e", ex), glyph("r", rx), glyph("o", ox)
S = slash(bx)

(ROOT / "public/brand").mkdir(parents=True, exist_ok=True)
(ROOT / "public/brand/vero-mark.svg").write_text(
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {num(mark_w)} {CAP}" fill="currentColor">'
    f'<title>Vero</title><path d="{S}"/><path d="{V}"/></svg>\n'
)
(ROOT / "public/brand/vero-wordmark.svg").write_text(
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {num(word_w)} {VIEW_H}" fill="currentColor">'
    f'<title>Vero</title><path d="{S}"/><path d="{V}"/><path d="{e}"/><path d="{r}"/><path d="{o}"/></svg>\n'
)
(ROOT / "components/brand").mkdir(parents=True, exist_ok=True)
(ROOT / "components/brand/vero-logo-geometry.ts").write_text(
    "// Generated by scripts/brand/generate-logo.py from Cal Sans. Don't edit by hand.\n"
    "export const VERO_LOGO = {\n"
    f"  /** viewBox height: cap height {CAP} + overshoot */\n  viewH: {VIEW_H},\n"
    f"  /** \\V mark width and \\Vero wordmark width, in viewBox units */\n"
    f"  markW: {num(mark_w)},\n  wordW: {num(word_w)},\n"
    f"  slash: \"{S}\",\n  V: \"{V}\",\n  e: \"{e}\",\n  r: \"{r}\",\n  o: \"{o}\",\n"
    f"  /** Region right of the V's right stroke: the letters are visible only here. */\n  clip: \"{clip}\",\n"
    f"  /** x offset that tucks \"ero\" fully behind the V. */\n  stripDX: {num(strip_dx)},\n"
    f"  /** x offset that slides the slash into the V's left stroke (they're parallel). */\n  merge: {num(merge)},\n"
    "} as const;\n"
)
print(f"mark {num(mark_w)} x {CAP}, wordmark {num(word_w)} x {VIEW_H}, stripDX {num(strip_dx)}, merge {num(merge)}")
